language: node_js
node_js:
  - "node"
  - "lts/*"
install:
  - npm ci
cache:
  directories:
    - "node_modules"
before_install:
  - npm prune
script:
  - npm run build
  - npm test
deploy:
  skip_cleanup: true
  provider: surge
  project: ./build/
  domain: https://keycodes.surge.sh
  on:
    node: "lts/*"
